// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9RXUfD-JnUNUCzTbq8ptBA3_fWrMB8uA',
    appId: '1:950167194392:web:ec879526e393de42f56c6d',
    messagingSenderId: '950167194392',
    projectId: 'fir-24ef9',
    authDomain: 'fir-24ef9.firebaseapp.com',
    storageBucket: 'fir-24ef9.appspot.com',
    measurementId: 'G-Y0EH4HL697',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6snP8dJ9ShRMaPzWwFl4k7wC9Lp05XCY',
    appId: '1:950167194392:android:7cdae160561ecfbff56c6d',
    messagingSenderId: '950167194392',
    projectId: 'fir-24ef9',
    storageBucket: 'fir-24ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMcWWgv1-ys8InqJfaCRtizmgOI7bAMc',
    appId: '1:950167194392:ios:cd89eda0d9d4be53f56c6d',
    messagingSenderId: '950167194392',
    projectId: 'fir-24ef9',
    storageBucket: 'fir-24ef9.appspot.com',
    iosClientId: '950167194392-s9hgmnkcot1n56h4pi2dlk2jsn8pvst8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPMcWWgv1-ys8InqJfaCRtizmgOI7bAMc',
    appId: '1:950167194392:ios:0300193044711e4df56c6d',
    messagingSenderId: '950167194392',
    projectId: 'fir-24ef9',
    storageBucket: 'fir-24ef9.appspot.com',
    iosClientId: '950167194392-u77gmk3a113uen6ahf17alhfidamsjfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire.RunnerTests',
  );
}
